/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package armadopalletv1;

import java.awt.Dimension;
import java.awt.Graphics;
import java.net.ContentHandlerFactory;
import javax.swing.ImageIcon;
import javax.swing.Icon;
import java.util.Timer;
import  java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Color;
import java.awt.Image;
/**
 *
 * @author Fredy
 */
public class Inicio extends javax.swing.JFrame {

 static int contador=0;

    public Inicio() {
        this.setUndecorated(true);    //ELIMINO BARRA DE TITULO
        this.getContentPane().setBackground(Color.WHITE);// FONDO JFRAME
        initComponents();
        //------------- Icono -------------------
      
         ImageIcon imageIcon;
        imageIcon =new  ImageIcon(getClass().getResource("/iconos/iconoLisanti.png")); 
        Image miImage = imageIcon.getImage();
        this.setIconImage((miImage));
        
         int velocidad=1;
          TimerTask tarea;
          TimerTask finTarea;
          
      Timer timer;
         
        
         
         int velmil=  velocidad * 1000; // tiempo en pasar imagenes
         int timeFinish= velocidad*5000; //tiempo en ejecutar mi otra accion
         
         
         tarea = new TimerTask() {
            @Override
            
            public void run() {
                Icon icono;            
     
                for (int i = 1; i <= 79; i++) {
                    String valor= Integer.toString(i);
                    icono =new  ImageIcon(getClass().getResource("/iconos/"+valor+".png"));
                    jicono.setIcon(icono);
                    try {
                        Thread.sleep(20);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }        
            }
        
        };
         
         timer = new Timer();
         timer.scheduleAtFixedRate(tarea,0,velmil);
      /// --------------- FINALIZAMOS LA TAREA -------------------------
      
      finTarea = new TimerTask() {
            @Override
            public void run() {
                
//                System.out.println("FINALIZANDO TAREA");
            }
        };

      timer.schedule(finTarea, timeFinish);
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jicono = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/armadopalletv1/lisantiImage.png"))); // NOI18N

        jicono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/00.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bandera2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jicono)))
                .addContainerGap(345, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(122, 122, 122)
                .addComponent(jicono)
                .addContainerGap(220, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jicono;
    // End of variables declaration//GEN-END:variables
}
