/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package armadopalletv1;

import java.awt.Color;
import java.awt.print.Book;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import java.awt.print.PrinterJob;
import java.text.MessageFormat;
import java.util.Enumeration;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import sumaProductos.SumarPallets;

/**
 *
 * @author Fredy
 */
public class JDialogUnir extends javax.swing.JDialog {

  
    DefaultTableModel model;
     String datosTabla[][]={};
    String titulosTabla[]={"DESCRIPTION","QTY","SLOT"};
    DefaultTableModel tablaProducto= new DefaultTableModel(datosTabla, titulosTabla);
   protected static String NoRuta ="nada";
    /**
     * Creates new form JDialogUnir
     */
    public JDialogUnir(java.awt.Frame parent, boolean modal) {
      
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);// FONDO JFRAME
        jBPrint.setBackground(Color.WHITE);
      
      JTablaUnir.setModel(tablaProducto);
         
//         setCellRender(JTablaUnir);
          ModificarTabla();         
           centrar_datos();
                    
    }

       public void centrar_datos(){
 
        DefaultTableCellRenderer modelocentrar = new DefaultTableCellRenderer();
        modelocentrar.setHorizontalAlignment(SwingConstants.CENTER);
        JTablaUnir.getColumnModel().getColumn(1).setCellRenderer(modelocentrar);
    }
       
     public void ModificarTabla(){
//     DefaultTableCellRenderer alinearCentro;    
//      alinearCentro = new DefaultTableCellRenderer();
//      alinearCentro.setHorizontalAlignment(SwingConstants.CENTER);
     //---------------- TAMAÑO CELDAS ------------------------------
     JTablaUnir.getColumnModel().getColumn(0).setPreferredWidth(200); //FUNCIONA
     JTablaUnir.getColumnModel().getColumn(1).setPreferredWidth(10);     
     JTablaUnir.getColumnModel().getColumn(2).setPreferredWidth(20); 
     
//     JTablaUnir.getColumnModel().getColumn(1).setCellRenderer(alinearCentro);
     setBackground(Color.white);//color de fondo
     JTablaUnir.setForeground(Color.black);
     //NOTA: LOS VALORES DEL TAMAÑO DE MI JFRAMEN ES DE 584 PX DEFAULT
     
     //---------------- AÑADIR NO CAJAS -------------------------
            
        String ruta= jLabelRuta.getText();
        
        String descripcion="LISANTI FOOD SERVICE";
        String cantidad="";
        String locacion="RT:";
       Object CantidadCajas[]= {descripcion,cantidad,locacion};
       Object espacio[]={"","",""};
       tablaProducto.addRow(CantidadCajas);
       tablaProducto.addRow(espacio);
     
     }
     
     //------------------ PINTAR CELDAS ----------------------------
       
        public void setCellRender(JTable table) {
            
        Enumeration<TableColumn> en = table.getColumnModel().getColumns();
        
        while (en.hasMoreElements()) {
            TableColumn tc = en.nextElement();
            tc.setCellRenderer(new CellRenderer());
            
        }
      
    }        
      public void modificarRuta(String miRuta){
      
      jLabelRuta.setText(miRuta);
      }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTablaUnir = new javax.swing.JTable();
        jBPrint = new javax.swing.JButton();
        jLabelRuta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("PRINT");

        JTablaUnir.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        JTablaUnir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTablaUnir.setAlignmentX(4.0F);
        jScrollPane1.setViewportView(JTablaUnir);

        jBPrint.setText("PRINT");
        jBPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRuta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBPrint)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabelRuta))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBPrint)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPrintActionPerformed
         try {
             PrinterJob printer = PrinterJob.getPrinterJob(); 
            
               //Set 1/2 " margins and orientation 

              PageFormat pf = printer.defaultPage(); 
              pf.setOrientation(PageFormat.PORTRAIT); 
             Paper paper = new Paper(); 
             double margin = 36; // half inch 
              paper.setImageableArea(margin, margin, paper.getWidth() - margin * 2, paper.getHeight() - margin * 2); 
             pf.setPaper(paper); 
             
             Book printJob = new Book(); 
            
//             for (JTable t : getAllTables()) 
          
           printJob.append(JTablaUnir.getPrintable(JTable.PrintMode.NORMAL, null, null), pf,6);           
           
           
             printer.setPageable(printJob); 
             System.out.println(printJob.getNumberOfPages());
             if (printer.printDialog()) 
             printer.print();
             
        } catch (Exception e) {
             e.printStackTrace(); 
        } 
      
    }//GEN-LAST:event_jBPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogUnir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogUnir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogUnir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogUnir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogUnir dialog = new JDialogUnir(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTablaUnir;
    private javax.swing.JButton jBPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelRuta;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
