/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package armadopalletv1;

import Days.JFrameMonday;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Fredy
 */
public class JFrameDays extends javax.swing.JFrame {

    /**
     * Creates new form JFrameDays
     */
    public JFrameDays() {
        initComponents();
        
           this.getContentPane().setBackground(Color.WHITE);// FONDO JFRAME
         PanelBotones.setBackground(Color.WHITE);
         btMonday.setBackground(Color.WHITE);
         btTuesday.setBackground(Color.WHITE);
         btWednesday.setBackground(Color.WHITE);
         btThursday.setBackground(Color.WHITE);
         btFriday.setBackground(Color.WHITE);
         
         //----------------- Icono --------------------
         
        ImageIcon imageIcon;
        imageIcon =new  ImageIcon(getClass().getResource("/iconos/iconoLisanti.png")); 
        Image miImage = imageIcon.getImage();
        this.setIconImage((miImage));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        PanelBotones = new javax.swing.JPanel();
        btMonday = new javax.swing.JButton();
        btTuesday = new javax.swing.JButton();
        btWednesday = new javax.swing.JButton();
        btThursday = new javax.swing.JButton();
        btFriday = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 0));
        jLabel2.setText("DAYLY ROUTES BY ORDER");

        btMonday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btMonday.setForeground(new java.awt.Color(255, 51, 51));
        btMonday.setText("MONDAY");
        btMonday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMondayActionPerformed(evt);
            }
        });

        btTuesday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btTuesday.setForeground(new java.awt.Color(255, 0, 0));
        btTuesday.setText("TUESDAY");
        btTuesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTuesdayActionPerformed(evt);
            }
        });

        btWednesday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btWednesday.setForeground(new java.awt.Color(255, 0, 0));
        btWednesday.setText("WEDNESDAY");
        btWednesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btWednesdayActionPerformed(evt);
            }
        });

        btThursday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btThursday.setForeground(new java.awt.Color(255, 0, 0));
        btThursday.setText("THURSDAY");
        btThursday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThursdayActionPerformed(evt);
            }
        });

        btFriday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btFriday.setForeground(new java.awt.Color(255, 0, 0));
        btFriday.setText("FRIDAY");
        btFriday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFridayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBotonesLayout = new javax.swing.GroupLayout(PanelBotones);
        PanelBotones.setLayout(PanelBotonesLayout);
        PanelBotonesLayout.setHorizontalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesLayout.createSequentialGroup()
                .addGroup(PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBotonesLayout.createSequentialGroup()
                        .addComponent(btMonday, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btTuesday, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btWednesday, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBotonesLayout.createSequentialGroup()
                        .addComponent(btThursday, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btFriday, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelBotonesLayout.setVerticalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesLayout.createSequentialGroup()
                .addGroup(PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMonday, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTuesday, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btWednesday, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThursday, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFriday, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(PanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btMondayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMondayActionPerformed

       JFrameMonday jFrameMonday = new JFrameMonday();
       jFrameMonday.setVisible(true);
      this.setVisible(false);
       this.dispose();
       String stringDay;
       stringDay= btMonday.getText();
       jFrameMonday.modificarTitulo(stringDay);  // DIA
       //---------- ASIGNAMOS TITULO A LOS BOTONES ------------
       //SE RECIBE COMO PARAMETRO EL BOTON Y EL TEXTO QUE SE QUIERE MODIFICAR
       jFrameMonday.modificarRutas(1,"09");
       jFrameMonday.modificarRutas(2,"15");
       jFrameMonday.modificarRutas(3,"14");
       jFrameMonday.modificarRutas(4,"61");
       jFrameMonday.modificarRutas(5,"04");
       jFrameMonday.modificarRutas(6,"08");
       jFrameMonday.modificarRutas(7,"18");
       jFrameMonday.modificarRutas(8,"16");
       jFrameMonday.modificarRutas(9,"07");
       jFrameMonday.modificarRutas(10,"17");
       jFrameMonday.modificarRutas(11,"10");
       jFrameMonday.modificarRutas(12,"13");
       jFrameMonday.modificarRutas(13,"12");
       jFrameMonday.modificarRutas(14,"71");
       jFrameMonday.modificarRutas(15,"19");
       jFrameMonday.modificarRutas(16,"81");
       jFrameMonday.modificarRutas(17,"91");
       jFrameMonday.modificarRutas(18,"09");
       jFrameMonday.modificarRutas(19,"11");
       jFrameMonday.modificarRutas(20,"");
       jFrameMonday.modificarRutas(21,"");
       jFrameMonday.modificarRutas(22,"");
       jFrameMonday.modificarRutas(23,"");
       jFrameMonday.modificarRutas(24,"");
    }//GEN-LAST:event_btMondayActionPerformed

    private void btTuesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTuesdayActionPerformed
     
        JFrameMonday jFrameMonday = new JFrameMonday();
       jFrameMonday.setVisible(true);
       this.setVisible(false);
      // this.dispose();
       String stringDay;
       stringDay= btTuesday.getText();
       jFrameMonday.modificarTitulo(stringDay);  // DIA
       //---------- ASIGNAMOS TITULO A LOS BOTONES ------------
       //SE RECIBE COMO PARAMETRO EL BOTON Y EL TEXTO QUE SE QUIERE MODIFICAR
       jFrameMonday.modificarRutas(1,"97");
       jFrameMonday.modificarRutas(2,"23");
       jFrameMonday.modificarRutas(3,"69");
       jFrameMonday.modificarRutas(4,"27");
       jFrameMonday.modificarRutas(5,"29");
       jFrameMonday.modificarRutas(6,"82");
       jFrameMonday.modificarRutas(7,"26");
       jFrameMonday.modificarRutas(8,"24");
       jFrameMonday.modificarRutas(9,"64");
       jFrameMonday.modificarRutas(10,"22");
       jFrameMonday.modificarRutas(11,"62");
       jFrameMonday.modificarRutas(12,"70");
       jFrameMonday.modificarRutas(13,"28");
       jFrameMonday.modificarRutas(14,"20");
       jFrameMonday.modificarRutas(15,"25");
       jFrameMonday.modificarRutas(16,"92");
       jFrameMonday.modificarRutas(17,"21");
       jFrameMonday.modificarRutas(18,"72");
       jFrameMonday.modificarRutas(19,"98");
       jFrameMonday.modificarRutas(20,"");
       jFrameMonday.modificarRutas(21,"");
       jFrameMonday.modificarRutas(22,"");
       jFrameMonday.modificarRutas(23,"");
       jFrameMonday.modificarRutas(24,"");  
    }//GEN-LAST:event_btTuesdayActionPerformed

    private void btWednesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btWednesdayActionPerformed
        
       JFrameMonday jFrameMonday = new JFrameMonday();
       jFrameMonday.setVisible(true);
       this.setVisible(false);
      // this.dispose();
       String stringDay;
       stringDay= btWednesday.getText();
       jFrameMonday.modificarTitulo(stringDay);  // DIA
       //---------- ASIGNAMOS TITULO A LOS BOTONES ------------
       //SE RECIBE COMO PARAMETRO EL BOTON Y EL TEXTO QUE SE QUIERE MODIFICAR
       jFrameMonday.modificarRutas(1,"68");
       jFrameMonday.modificarRutas(2,"93");
       jFrameMonday.modificarRutas(3,"37");
       jFrameMonday.modificarRutas(4,"84");
       jFrameMonday.modificarRutas(5,"73");
       jFrameMonday.modificarRutas(6,"63");
       jFrameMonday.modificarRutas(7,"03");
       jFrameMonday.modificarRutas(8,"67");
       jFrameMonday.modificarRutas(9,"34");
       jFrameMonday.modificarRutas(10,"31");
       jFrameMonday.modificarRutas(11,"86");
       jFrameMonday.modificarRutas(12,"87");
       jFrameMonday.modificarRutas(13,"66");
       jFrameMonday.modificarRutas(14,"35");
       jFrameMonday.modificarRutas(15,"32");
       jFrameMonday.modificarRutas(16,"83");
       jFrameMonday.modificarRutas(17,"85");
       jFrameMonday.modificarRutas(18,"39");
       jFrameMonday.modificarRutas(19,"30");
       jFrameMonday.modificarRutas(20,"38");
       jFrameMonday.modificarRutas(21,"36");
       jFrameMonday.modificarRutas(22,"33");
       jFrameMonday.modificarRutas(23,"");
       jFrameMonday.modificarRutas(24,""); 
        
        
    }//GEN-LAST:event_btWednesdayActionPerformed

    private void btThursdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThursdayActionPerformed
           JFrameMonday jFrameMonday = new JFrameMonday();
       jFrameMonday.setVisible(true);
       this.setVisible(false);
      // this.dispose();
       String stringDay;
       stringDay= btThursday.getText();
       jFrameMonday.modificarTitulo(stringDay);  // DIA
       //---------- ASIGNAMOS TITULO A LOS BOTONES ------------
       //SE RECIBE COMO PARAMETRO EL BOTON Y EL TEXTO QUE SE QUIERE MODIFICAR
       jFrameMonday.modificarRutas(1,"45");
       jFrameMonday.modificarRutas(2,"94");
       jFrameMonday.modificarRutas(3,"40");
       jFrameMonday.modificarRutas(4,"48");
       jFrameMonday.modificarRutas(5,"96");
       jFrameMonday.modificarRutas(6,"47");
       jFrameMonday.modificarRutas(7,"44");
       jFrameMonday.modificarRutas(8,"43");
       jFrameMonday.modificarRutas(9,"41");
       jFrameMonday.modificarRutas(10,"46");
       jFrameMonday.modificarRutas(11,"49");
       jFrameMonday.modificarRutas(12,"95");
       jFrameMonday.modificarRutas(13,"42");
       jFrameMonday.modificarRutas(14,"");
       jFrameMonday.modificarRutas(15,"");
       jFrameMonday.modificarRutas(16,"");
       jFrameMonday.modificarRutas(17,"");
       jFrameMonday.modificarRutas(18,"");
       jFrameMonday.modificarRutas(19,"");
       jFrameMonday.modificarRutas(20,"");
       jFrameMonday.modificarRutas(21,"");
       jFrameMonday.modificarRutas(22,"");
       jFrameMonday.modificarRutas(23,"");
       jFrameMonday.modificarRutas(24,""); 
    }//GEN-LAST:event_btThursdayActionPerformed

    private void btFridayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFridayActionPerformed
           JFrameMonday jFrameMonday = new JFrameMonday();
       jFrameMonday.setVisible(true);
       this.setVisible(false);
      // this.dispose();
       String stringDay;
       stringDay= btFriday.getText();
       jFrameMonday.modificarTitulo(stringDay);  // DIA
       //---------- ASIGNAMOS TITULO A LOS BOTONES ------------
       //SE RECIBE COMO PARAMETRO EL BOTON Y EL TEXTO QUE SE QUIERE MODIFICAR
       jFrameMonday.modificarRutas(1,"58");
       jFrameMonday.modificarRutas(2,"56");
       jFrameMonday.modificarRutas(3,"60");
       jFrameMonday.modificarRutas(4,"54");
       jFrameMonday.modificarRutas(5,"50");
       jFrameMonday.modificarRutas(6,"51");
       jFrameMonday.modificarRutas(7,"52");
       jFrameMonday.modificarRutas(8,"57");
       jFrameMonday.modificarRutas(9,"53");
       jFrameMonday.modificarRutas(10,"55");
       jFrameMonday.modificarRutas(11,"59");
       jFrameMonday.modificarRutas(12,"");
       jFrameMonday.modificarRutas(13,"");
       jFrameMonday.modificarRutas(14,"");
       jFrameMonday.modificarRutas(15,"");
       jFrameMonday.modificarRutas(16,"");
       jFrameMonday.modificarRutas(17,"");
       jFrameMonday.modificarRutas(18,"");
       jFrameMonday.modificarRutas(19,"");
       jFrameMonday.modificarRutas(20,"");
       jFrameMonday.modificarRutas(21,"");
       jFrameMonday.modificarRutas(22,"");
       jFrameMonday.modificarRutas(23,"");
       jFrameMonday.modificarRutas(24,""); 
    }//GEN-LAST:event_btFridayActionPerformed

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameDays().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JButton btFriday;
    private javax.swing.JButton btMonday;
    private javax.swing.JButton btThursday;
    private javax.swing.JButton btTuesday;
    private javax.swing.JButton btWednesday;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
